# Docker Compose configuration for Gaussian Splatting

services:
  gaussian-splatting:
    image: judein/splatting_container_brush:amd64
    # GPU support is not available in this image
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: ["gpu"]
              count: all
    container_name: gaussian_splatting
    ports:
       - "9876:9876"
    volumes:
      - ./ingest:/workspace/ingest
      - ./output:/workspace/out