# Docker Compose configuration for Gaussian Splatting

services:
  gaussian-splatting:
    image: docker.pkg.github.com/splatting_container:latest-arm64
    container_name: gaussian_splatting
    ports:
       - "9876:9876"
       - "8000:8000"
    volumes:
      - ./ingest:/workspace/ingest
      - ./result:/workspace/out
      - ./colmap:/workspace/colmap_workspace

    devices:
      - /dev/dri/:/dev/dri/
