# Docker Compose configuration for Gaussian Splatting

services:
  gaussian-splatting:
    image: judein/splatting_container_brush:arm64
    container_name: gaussian_splatting
    ports:
       - "9876:9876"
    volumes:
      - ./ingest:/workspace/ingest
      - ./result:/workspace/out
      - ./colmap:/workspace/colmap_workspace

    devices:
      - /dev/dri/:/dev/dri/
