# Docker Compose configuration for Gaussian Splatting

services:
  gaussian-splatting:
    image: judein/splatting_container_brush:amd64
    ports:
       - "9876:9876"
    volumes:
      - ./ingest:/workspace/ingest
      - ./output:/workspace/out
    devices:
      - /dev/dri/:/dev/dri/