# Docker Compose configuration for Gaussian Splatting

services:
  gaussian-splatting:
    image: docker.pkg.github.com/splatting_container:latest-amd64
    ports:
       - "9876:9876"
       - "8000:8000"
    volumes:
      - ./ingest:/workspace/ingest
      - ./output:/workspace/out
    devices:
      - /dev/dri/:/dev/dri/