# Docker Compose configuration for Gaussian Splatting

services:
  gaussian-splatting:
    image: docker.pkg.github.com/splatting_container:latest-amd64
    # GPU support is not available in this image
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: ["gpu"]
              count: all
    container_name: gaussian_splatting
    ports:
       - "9876:9876"
       - "8000:8000"
    volumes:
      - ./ingest:/workspace/ingest
      - ./output:/workspace/out