name: Build and Push Docker Image
on:
  push:
    branches:
      - main
      - API
    paths:
      - 'Dockerfile'
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Docker Buildx
        run: |
          curl -fsL https://github.com/docker/buildx/releases/download/v0.25.0/buildx-v0.25.0.linux-amd64 > /usr/local/bin/docker-buildx
            chmod +x /usr/local/bin/docker-buildx

      - name: Log in to Docker registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login docker.pkg.github.com -u ${{ github.actor }} --password-stdin


      - name: Build and push for amd64
        run: |
          docker buildx build --platform linux/amd64 --tag docker.pkg.github.com/splatting_container:latest-amd64 . &&
          docker push docker.pkg.github.com/splatting_container:latest-amd64

      - name: Build and push for arm64
        run: |
          docker buildx build --platform linux/arm64 --tag docker.pkg.github.com/splatting_container:latest-arm64 . &&
          docker push docker.pkg.github.com/splatting_container:latest-arm64
